---
Resources:
Instance1:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: CloudFormationKeyPair
    ImageId: ami-006a0174c6c25ac06
    InstanceType: t2.micro
    Tags:
      - Key: "Name"
        Value: "Example"
    SecurityGroups:
      - !Ref AllowSSH

AllowSSH:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Enable SSH access
    SecurityGroupIngress:
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
...