---
Resources:
  EasyVPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.13.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: EasyVPC1

  EasySubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-1a
      CidrBlock: 172.13.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: EasySubnet1

      VpcId: !Ref EasyVPC1

  EasyEC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-1a
      Tenancy: default
      ImageId: ami-00e1a1c196475d9e1
      InstanceType: t2.micro
      KeyName: asbandia-key-pair
      SubnetId: !Ref EasySubnet1
      SecurityGroupIds:
        - !Ref EasySecGroup1
      Tags:
        - Key: Name
          Value: EasyEC2Instance1

  EasySecGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EasySecGroup1


  EasyIG1:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: EasyInternetGateway1

  AssignIGtoVPC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref EasyIG1
      VpcId: !Ref EasyVPC1

  EasyRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref EasyVPC1
      Tags:
        - Key: Name
          Value: EasyRouteTable1

  EasyRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref EasyIG1
      RouteTableId: !Ref EasyRouteTable1
...